name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests and Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache-dependency-path: go.sum

    - name: Verify Go modules
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: go test -v -race ./...

    - name: Run vet
      run: go vet ./...

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version tag
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        echo "Using tag: ${TAG}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-app:${{ steps.version.outputs.TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-app:latest

    - name: Verify pushed image
      run: |
        echo "Image successfully pushed to DockerHub"
