name: Go CI/CD with Docker Publishing

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  docker-publish:
    name: Publish to DockerHub
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

    - name: Verify uploaded image
      run: |
        echo "âœ… Image successfully pushed to DockerHub"
        echo "í³¦ Image tag: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest"
